<?php 

function support_simulador(){
    $formulario = drupal_get_form('support_simulador_form');
    print render($formulario);
}

   
function support_simulador_form(){

    //calcular o ano minimo de todos os modelos
   taxonomy_get_tree(4);


    $form['ano'] = array(
           '#type' => 'select',
           '#title' => 'Ano',
           '#options' => array(
                0 => '---',
                1 => 'Falta calcular os anos'
            ),
           '#default_value' => 2,
            '#ajax' => array(
            'callback' => 'support_simulador_select',
            'wrapper' => 'replace_textfield_div',
            )
    );
    $form['marca'] = array(
           '#type' => 'select',
           '#title' => 'Marca',
           '#options' => array(
                0 => ' --- '
            ),
           '#default_value' => 0,
           '#prefix' => '<div id="replace_textfield_div">',
            '#suffix' => '</div>',
    );
	$form['modelo'] = array(
           '#type' => 'select',
           '#title' => 'Modelo',
           '#options' => array(
                0 => ' --- '
            ),
           '#default_value' => 0,
           '#prefix' => '<div id="replace_textfield_div">',
            '#suffix' => '</div>',
    );
	    $form['cilindrada'] = array(
           '#type' => 'select',
           '#title' => 'Cilindrada',
           '#options' => array(
                0 => ' --- '
            ),
           '#default_value' => 0,
           '#prefix' => '<div id="replace_textfield_div">',
            '#suffix' => '</div>',
    );
    $form['submit'] = array(
	'#type' => 'submit', 
	'#value' => '',
    '#prefix' => '<div id="submit_simul_div">',
    '#suffix' => '</div>',
	);
      

   return $form;
}

function support_simulador_select($form, $form_state){
    

    $form['marca']['#options'] = array(0 => 'Falta calcular as marcas');
    return $form['marca'];

}